// automatically generated by the FlatBuffers compiler, do not modify

package hyperhdrnet;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Reply extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Reply getRootAsReply(ByteBuffer _bb) { return getRootAsReply(_bb, new Reply()); }
  public static Reply getRootAsReply(ByteBuffer _bb, Reply obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Reply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String error() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer errorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int video() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public int registered() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : -1; }

  public static int createReply(FlatBufferBuilder builder,
      int errorOffset,
      int video,
      int registered) {
    builder.startTable(3);
    Reply.addRegistered(builder, registered);
    Reply.addVideo(builder, video);
    Reply.addError(builder, errorOffset);
    return Reply.endReply(builder);
  }

  public static void startReply(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(0, errorOffset, 0); }
  public static void addVideo(FlatBufferBuilder builder, int video) { builder.addInt(1, video, -1); }
  public static void addRegistered(FlatBufferBuilder builder, int registered) { builder.addInt(2, registered, -1); }
  public static int endReply(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishReplyBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedReplyBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Reply get(int j) { return get(new Reply(), j); }
    public Reply get(Reply obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

